deployment/cf/README.md

Document deployment to CF with external PostgreSQL

Update cf deploy docu

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
ISSUE_TEMPLATE.md
PULL_REQUEST_TEMPLATE.md

The following Pull Request suggests changes that will add files some mandatory and recommended files to the repository in order for it to comply with the general Open Source Community guidelines.
Status:

Open Source documents

---

main.go

No copyright notice in main.go
Use checklists as a means to represent the status of your Pull Request.
For example:
- [n/a] Initial implementation
- [n/a] Refactoring
- [n/a] Unit tests

Add copyright on main.go

---

storage/postgres/abstract_test.go
storage/postgres/postgres_suite_test.go
storage/postgres/storage_test.go

Increase test coverage
Unit tests for postgres package.
- [n/a] Initial implementation
- [n/a] Refactoring

Add unit tests for postgres storage

---

app/app.go
application.yml
authentication/types.go
config/config.go
config/config_test.go
filters/auth/auth.go
filters/auth/filters.go
pkg/servicemanager/sm_test.go
test/common/application.yml
test/healthcheck_test/healthcheck_test.go
test/info_test/info_test.go

OAuth authenticator was built on every requests and this was not ok. Now this is done during SM startup

Refactor authencation

---

api/broker/broker_controller.go
api/catalog/catalog_controller.go
api/platform/platform_controller.go
authentication/basic/basic.go
storage/interfaces.go
storage/postgres/abstract.go
storage/postgres/abstract_test.go
storage/postgres/broker.go
storage/postgres/credentials.go
storage/postgres/migrations/001_initial_schema.down.sql
storage/postgres/migrations/001_initial_schema.up.sql
storage/postgres/migrations/002_add_catalog_to_brokers.down.sql
storage/postgres/migrations/002_add_catalog_to_brokers.up.sql
storage/postgres/platform.go
storage/postgres/storage.go
storage/postgres/storage_test.go
storage/postgres/types.go
storage/storagefakes/fake_platform.go

Remove credentials table

---

Dockerfile
deployment/k8s/charts/service-manager/requirements.lock
deployment/k8s/charts/service-manager/templates/sm02-configmap.yaml
deployment/k8s/charts/service-manager/templates/sm03-deployment.yaml
deployment/k8s/charts/service-manager/values.yaml
docs/plugins.md

- [n/a] Refactoring
- [n/a] Unit tests

Fix k8s deployment

---

.gometalinter.json
api/osb/osb.go
pkg/web/api.go
pkg/web/plugin.go
test/common/common.go
test/common/test_context.go
test/osb_test/osb_test.go
test/plugin_test/plugin_test.go

Motivation:
Async service instance creation from platforms calls last_operation endpoint of the broker
Steps:

Proxy last operation call

---

server/server.go

On Mac you get a nasty popup each time
you start it unless it listens on localhost

Configure server host

---

storage/registry_test.go

Currently when running go tests with race condition check (ginkgo -r -race) some fail with Data Race. This PR addresses 
the issue.
```
==================
WARNING: DATA RACE
Read at 0x00c04228e450 by goroutine 8:
runtime.convT2Estring()
C:/Go/src/runtime/iface.go:354 +0x0
github.com/Peripli/service-manager/storage_test.(*logInterceptor).VerifyData()
C:/Users/i321655/go/lib/src/github.com/Peripli/service-manager/storage/registry_test.go:61 +0x156
github.com/Peripli/service-manager/storage_test.glob..func1.4.2.1()
C:/Users/i321655/go/lib/src/github.com/Peripli/service-manager/storage/registry_test.go:150 +0x254
github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync()
C:/Users/i321655/go/lib/src/github.com/Peripli/service-manager/vendor/github.co …
```

Fix race conditions in tests

---

Dockerfile

Import root certificates as part of the container build

---

docs/usage/example-usage.md

Add link to video that explains the scenario

Add link to video that explains the scenario

---

api/broker/broker_controller.go
test/auth_test/auth_test.go
test/broker_test/broker_test.go
test/common/common.go
test/common/test_context.go

Transform credentials after fetching catalog

---

test/auth_test/auth_test.go
test/broker_test/broker_test.go
test/common/broker.go
test/common/common.go
test/common/test_context.go
test/filter_test/filter_test.go
test/osb_test/osb_test.go
test/plugin_test/plugin_test.go

Currently there are multiple implementations of test broker servers which brings confusion and unnecessary code duplication. 
This PR introduces a single unified test broker server implementation to be used in all broker related tests.

Improve broker tests

---

deployment/cf/manifest.yml

Deploying SM as docker image used an older version.

Update manifest.yml version

---

pkg/util/slice/strings.go

Add util for strings suffix check

---

.travis.yml
Dockerfile
api/osb/osb_controller.go
deployment/cf/manifest.yml
test/osb_test/osb_test.go
test/plugin_test/plugin_test.go

* Improve Logging in ReverseProxy
* Add ErrorHandler to ReverseProxy to generate meaningful error message when service broker is unreachable
* Add tests to verify ReverseProxy proxies query parameters
* Bump to go 1.11

SM ReverseProxy: Improve logging and error messaging

---

pkg/util/api.go
pkg/util/api_test.go

Return empty response body for APIs returning 204 No Content

---

storage/postgres/storage_state.go

Fixes failing storage health check

Fix failing storage health check

---

api/osb/osb.go
pkg/web/api.go
pkg/web/plugin.go
test/common/broker.go
test/osb_test/osb_test.go
test/plugin_test/plugin_test.go

* This relates to #167 and implements the adapt_credentials endpoint.
One step closer to implementing the issue #167 
It forwards the additional endpoint adapt_credentials to the service broker.
n/a
n/a

Add adapt credentials endpoint

---

pkg/types/service_plan.go
storage/postgres/types.go
test/osb_test/osb_test.go

Fix broken Catalog when some properties are missing

---

pkg/query/selection_test.go
storage/postgres/abstract_test.go
storage/postgres/labels.go
storage/postgres/labels_test.go
test/visibility_test/visibility_test.go

Querying with multiple labels currently does not work. This addresses the issue.

Allow multiple labels querying

---

storage/postgres/storage.go

Useful for troubleshooting migration issues

Log db migration

---

docs/usage/labels.md

Fix typo in labels.md

---

pkg/security/interfaces.go
pkg/security/middlewares/authz.go
pkg/security/securityfakes/fake_authorizer.go
test/common/test_context.go

Required by authorizers to access the request body.
Change the Authorizer interface.

Pass web.Request to Authorizer interface

---

docs/install/sm.md

STORAGE_URI
Use checklists as a means to represent the status of your Pull Request.
For example:
Feel free to construct the checklist with whatever items seem most reasonable for your change. You could disassemble the Implementation part to even smaller separate checklist items if you're working on something big for example. But do make the effort to provide a checklist of some sort so that the core team as well as the community can have an idea …

Fix typo in sm.md

---

Makefile

* Makefile install fixed version of counterfeiter which will make life easier

Install fixed version of counterfeiter

---

storage/postgres/notification.go
storage/postgres/storage.go
storage/postgres/storage_test.go

* Add SelectContext to postgres storage.
* Fix notification PlatformID when null.

Add selectContext to pgStorage, fix null notification platform.Id

---

storage/postgres/abstract.go
storage/postgres/labels.go
storage/postgres/labels_test.go
test/query_test/query_test.go

* Fixes querying by field for numbers, timestamps by not trying to cast to text the db field.
* Does not work for labels currently as we cannot know whether the value we are trying to convert is number or something else for varchar fields
* Adds test for timestamps, but no test for number fields as we don't have any in our db model currently

Fix query number

---

config/config_test.go
pkg/sm/sm.go
storage/interfaces.go
storage/notification_cleaner.go
storage/notification_cleaner_test.go
storage/notification_queue_test.go
storage/storage_suit_test.go
test/common/test_context.go
test/notification_cleaner_test/notification_cleaner_test.go

This PR introduces notification cleaner which deletes old notifications from SM database

Notifications cleaner

---

test/common/common.go
test/common/test_context.go
test/osb_test/osb_test.go

* expose repository in test context
* fix issues in test context utils for platform and broker creation

Expose repository in test context

---

api/base_controller.go
pkg/util/errors.go
storage/interceptable_repository.go
storage/interceptable_repository_test.go
storage/interceptors/broker_public_plans_interceptor.go
storage/interceptors/broker_update_catalog_interceptor.go
storage/interceptors_delete.go
storage/interceptors_update.go
storage/postgres/abstract.go
test/interceptors_test/interceptors_test.go

change update and delete interceptor interfaces

---

test/common/catalog.go
test/notification_test/notification_test.go

* added test to verify creating a broker actually creates notifications for each visibility created relatively to the broker

Notifications Adjustments

---

docs/usage/walkthrough.md

This is merged: https://github.com/Peripli/service-broker-proxy/pull/67
https://github.com/Peripli/service-broker-proxy/pull/67

Change broker proxy prefix in walkthrough

---

api/notifications/notifications.go
test/ws_notification_test/ws_notification_test.go

SM always sends all existing notifications and the proxy applies them even when doing full resync.
If the proxy connects without last_notification_revision query parameter, SM does not send old notifications, but only new ones.

Do not send old notifications if proxy sends no revision

---

api/notifications/notifications.go
api/notifications/ws_connection.go

* Fix handled missed error
* Add recovery to HandleWS method so SM does not panic when a panic occurs in establish WS connection request

Fix npe from panic in gorountine

---

storage/postgres/migrations/010_public_visibility_fix.down.sql
storage/postgres/migrations/010_public_visibility_fix.up.sql
test/visibility_test/visibility_test.go

Fixes: https://github.com/Peripli/service-manager/issues/283

Fix public visibility update when platformID is null

---

pkg/util/api.go
pkg/util/api_test.go

Extend supported content types for APIs

---

deployment/k8s/charts/service-manager/Chart.yaml
deployment/k8s/charts/service-manager/requirements.lock
deployment/k8s/charts/service-manager/requirements.yaml
deployment/k8s/charts/service-manager/templates/_helpers.tpl
deployment/k8s/charts/service-manager/templates/sm01-secret.yaml
deployment/k8s/charts/service-manager/templates/sm03-deployment.yaml
deployment/k8s/charts/service-manager/values.yaml
docs/install/sm.md

Update service-manager kubernetes helm chart.
* Update postgres dependency
* Add ability to set pod security context
* Add ability to set pod image pull secret
* Update default service-manager image version

Update k8s deployment

---

docs/README.md

Going to ignore the template...this is just cleaning up a couple typos in a README.

Fix typos.

---

storage/postgres/abstract.go
storage/postgres/query_builder.go
storage/postgres/query_builder_test.go
test/delete_list.go
test/list.go

* Allow deletion by label query (delete resources by specifying matching label criteria
* Refactor query builder tests to be usable as documentation for the query by showing the exact queries built

Delete by Label Query/Criteria

---

api/osb/osb_controller.go

OSB requests were not traceable without setting log level to debug. Change some logs to info level.

Change some OSB request logs level to info

---

test/osb_test/osb_test.go

Fix async test race condition

---

Dockerfile

Fix security issues in golang
Update to latest patch version

Update golang to latest patch version

---

docs/development/db-schema.md

Describe db migrations and how to upgrade/downgrade manually.

Document db migrations

---

api/filters/basic_authentication.go
api/filters/tenant_filter.go
api/filters/tenant_filter_test.go
api/healthcheck/healthcheck_controller_test.go
pkg/multitenancy/token_extraction.go
pkg/multitenancy/token_extraction_test.go
pkg/security/authenticators/oidc_authenticator.go
pkg/security/filters/middlewares/authrization.go
pkg/security/filters/middlewares/middlewares_test.go
pkg/security/http/auth.go
pkg/security/http/httpfakes/fake_authorizer.go
pkg/web/user.go
storage/postgres/query_builder_test.go
test/list.go
test/test.go

Add AccessLevel to user context
Authorizers now return accesslevel

Introduce Access Level

---

.travis.yml
Dockerfile

Increase go version to 1.12

---

Gopkg.lock
api/api.go
api/service_instance_controller.go
pkg/types/service_instance.go
pkg/types/serviceinstance_gen.go
pkg/web/routes.go
storage/postgres/keystore_test.go
storage/postgres/migrations/20191118203400_service_instances.down.sql
storage/postgres/migrations/20191118203400_service_instances.up.sql
storage/postgres/service_instance.go
storage/postgres/serviceinstance_gen.go
storage/postgres/storage.go
test/broker_test/broker_test.go
test/common/test_context.go
test/list.go
test/platform_test/platform_test.go
test/service_instance_test/service_instance_test.go
test/service_offering_test/service_offering_test.go
test/service_plan_test/service_plan_test.go
test/test.go
test/visibility_test/visibility_test.go

Introduces Service Instance resource so Service Manager can start manage such entities.
https://github.com/Peripli/service-manager/pull/351

Introduce Service Instance resource

---

storage/postgres/migrations/20191017214200_notifications_sequence.down.sql

Fixes broken down migration script

Fix down migration for notification paging

---

storage/postgres/keystore_test.go
storage/postgres/migrations/20191206134500_remove_operations_unique.down.sql
storage/postgres/migrations/20191206134500_remove_operations_unique.up.sql

Remove unique constraint on operations table for external id

Remove unique constraint

---

api/osb/store_instances_plugin.go
test/osb_test/poll_instance_last_operation_test.go
test/service_instance_test/service_instance_test.go

Check if instance was not found and do not fail if not found

Do not fail on not found service instances

---

Gopkg.lock
Gopkg.toml
pkg/util/osb.go

Will be needed for OSB interceptor which will call broker endpoints.

Introduce flexible OSB Client constructor

---

Gopkg.lock
test/auth_test/auth_test.go

Add Service Instance C/U/D APIs tests

---

api/filters/check_binding_visibility_filter.go
api/filters/check_instance_visibility_filter.go
test/common/test_context.go
test/delete.go
test/delete_list.go
test/get.go
test/list.go
test/patch.go
test/service_binding_test/service_binding_test.go
test/service_instance_test/service_instance_test.go
test/test.go

*Return bad request for requests with no tenant identifier for instances and bindings*

Reject requests with no tenant for service and bindings

---

operations/maintainer.go
storage/encrypting_repository.go

Fix godoc. Some minor refinements

---

storage/interceptors/broker_public_plans_interceptor.go
test/notification_test/notification_test.go
test/public_plans_interceptor_test/public_plans_test.go

Add supported platforms pluggable function to public plans interceptor

---

test/common/oauth_server.go
test/common/test_context.go

Add convenience methods for OAuth test server. They are needed to implement a test for bug in the multi authenticator

Multi authenticator

---

pkg/sm/sm.go

Raw repository fetches credentials from DB encrypted and the integrity is calculated on the encrypted credentials. When fetching the entry from DB afterwards, the integrity is calculated on the decrypted credentials which results in a mismatch

Decrypt integral object credentials

---

storage/encrypting_repository.go
storage/integrity_repository.go
storage/interceptable_repository.go
storage/interceptable_repository_test.go
storage/interfaces.go
storage/postgres/query_builder.go
storage/postgres/storage.go
storage/storagefakes/fake_storage.go

Concurrent update/read operations were susceptible to sharelock deadlocking. 
Reference about locking: https://www.postgresql.org/docs/9.4/explicit-locking.html

Fix ShareLock deadlock

---

storage/encrypting_repository.go
storage/encrypting_repository_test.go
storage/integrity_repository.go
storage/integrity_repository_test.go
storage/interceptable_repository.go
storage/interfaces.go
storage/postgres/query_builder.go
storage/postgres/query_builder_test.go
storage/postgres/storage.go
storage/postgres/storage_state_test.go
storage/storagefakes/fake_storage.go

In some cases fetching entities is required but their labels are not used.
Introduce a new db api that fetches entities without labels.

Add ListNoLabels to storage

---

operations/config.go
pkg/sm/sm.go
pkg/types/platform.go
pkg/types/service_plan.go

SM platform type needs to be configurable

Allow to configure service-manager platform type

---

api/osb/check_instance_visibility_plugin.go
test/osb_test/update_instance_test.go

Currently the check assumed that if the plan is not updated it will not be presented in the request body. However CC sends the plan_id in the body even if it is not changed and remains the same. SM should make a difference between this situations because if not this makes the instance some sort of unusable.

Update instance check for visibility only if the plan of the instance is changed

---

storage/postgres/storage.go
test/common/application.yml
test/configuration_test/configuration_test.go
test/visibility_test/visibility_test.go

Insert labels in batches to avoid pq param limit

---

storage/interceptors/smaap_service_instance_interceptor.go
test/service_instance_test/service_instance_test.go

Fix async provision failures for temporary unavailable brokers
According to OSB Spec
If you use third party code with your contribution such as, components, libraries, or snippets make sure to mention that.
Make sure that …

Fix async provision failures for temporary unavailable brokers

---

storage/storagefakes/fake_storage.go

regenerate fake_stoarge with QueryForLIst

---

test/operations_test/cascade_test/cascade_suite_test.go
test/operations_test/cascade_test/cleanup_test.go
test/operations_test/cascade_test/interceptor_test.go
test/operations_test/cascade_test/polling_test.go

improve sa_termination tests

---

operations/cascade_utils.go
operations/scheduler.go
storage/interceptors/smaap_service_instance_interceptor.go
test/operations_test/cascade_test/cascade_suite_test.go

sa_termination test

---

storage/interceptors/unique_instance_names_interceptor.go

When checking for service instance name uniqueness during creation or update in SMaaP, the scope for uniqueness is defined to be the tenant. Some use cases may need to limit the scope even further, to provide "namespaces" within the tenant. Such scoping is achieved by using custom labels (as in the case of the tenant scope), but the name uniqueness checks do not "respect" those labels. 
This change changes the logic of the unique_instance_name_interceptor to re-use any labelQuery criteria that were added to the context, this way custom labelQueries added to support custom scopes will be included, making the scope for uniqueness check correct in such cases.

Resue context criteria for name uniqueness checks

---

operations/cascade_utils.go

handle duplicate operations in  cascade tree with the same type

---

api/base_controller.go
operations/scheduler.go
pkg/types/operation.go
storage/interceptors/smaap_service_binding_interceptor.go
storage/interceptors/smaap_service_instance_interceptor.go
storage/postgres/abstract.go
storage/postgres/keystore_test.go
storage/postgres/locker_test.go
storage/postgres/migrations/20200708749000_operations_context.up.sql
storage/postgres/migrations/20200708749000_operations_is_context.down.sql
storage/postgres/operation.go
test/common/operation.go
test/get.go
test/operations_test/operations_test.go
test/service_instance_and_binding_test/service_binding_test/service_binding_test.go
test/service_instance_and_binding_test/service_instance_test/service_instance_test.go

Create changes:
- Preserve ASYNC instances or bindings that fail during the creation
- Don't keep instances or bindings that require sync orphaned mitigation ( use the operation context for orphaned mitigation instead)
Delete changes:
- Delete service instances or bindings once orphaned mitigation is completed successfully
- Keep instances or bindings in case orphaned mitigation fails
Operation changes:
- Don't return the operation context on rest calls
- +1 JSON context column is added
* [X ] Integration tests

Lifecycle changes

---

storage/storagefakes/fake_storage.go

*Fix fake_storage.go to fulfil the missing generated implementations for GetEntities interface  *
If you use third party code with your contribution such as, components, libraries, or snippets make sure to mention that.
Make sure that your contribution complies with our [Contribution guidelines][1].
For as long as development of your Pull Request is still ongoing you MUST label it with a **wip** label as well as prefix the name of the PR with *[WIP]*.
For example: *[WIP] Service brokers API*
[1]: https://github.com/Peripli/service-manager/blob/master/CONTRIBUTING.md

Fix fake_storage to include fakes for GetEntities interface

---

operations/maintainer.go
pkg/query/selection.go
storage/sub_query.go
test/query_test/query_test.go

add tenant scoped services sub query and improving sub query mechanism
If you use third party code with your contribution such as, components, libraries, or snippets make sure to mention that.
Make sure that your contribution complies with our [Contribution guidelines][1].
For as long as development of your Pull Request is still ongoing you MUST label it with …

add tenant scoped services sub query and improving sub query mechanism

---

storage/service_plans/resolver.go

Add func for fetching supported platforms of plans with map [platform_id]Platform as output

fetch supported platforms for plans

---

storage/named_query.go
storage/postgres/keystore_test.go
storage/postgres/locker_test.go
storage/postgres/migrations/20200914413800_visibility_label_val_index.down.sql
storage/postgres/migrations/20200914413800_visibility_label_val_index.up.sql
storage/postgres/query_builder_test.go

Add additional named query for finding public visibilities and add index to val column of visibility_labels table

Visibility query

---

pkg/sm/sm.go
storage/interceptors/broker_notifications_interceptor.go
test/notification_test/notification_test.go

only send notifications to platforms that are active or that were active recently, i.e. no longer than the period for which we keep notifications for. If the platform was not connected for more than this period, the SM agent will anyways run full reconciliation so no notifications are needed.
Feel free to construct the checklist with whatever items seem most reasonable for your change. You could disassemble the Implementation part to even smaller …

improve broker notifications

---

api/healthcheck/platform_indicator_test.go
pkg/health/types.go
pkg/sm/sm.go

add aging for inactive platform before it fails healthcheck

add aging for inactive platform before it fails healthcheck

---

api/filters/rate_limiter_filter.go

Fix logic for sending log when client reach rate limit threshold
Fix the logic

Fix rate limit log logic

---

pkg/types/platform.go
test/platform_test/platform_test.go

Fix bug of platform password rotation

fix platform password rotation

---

api/healthcheck/helper.go
api/healthcheck/monitored_platform_indicator_test.go

Platofrm health fix

---

api/healthcheck/helper.go

count platform that were never online

Platforms inactive

---

storage/postgres/platform.go

support nullable strings for version in platform type

set version as nullable

---

api/base_controller.go
storage/named_query.go
test/query_test/query_test.go

fix fetching last op of object and considering object type besides its id

fix fetching last op

---

api/healthcheck/helper.go

Exclude platforms that were never activated from healthcheck.

Filter out platforms

---

operations/config.go
pkg/sm/sm.go
pkg/types/platform.go
pkg/types/service_plan_utils.go
storage/service_plans/resolver.go
test/configuration_test/configuration_test.go

support multiple aliases for sm platform

support multiple aliases for sm platform

---

api/filters/context_timeout_filter.go
pkg/server/server.go
pkg/sm/sm.go
test/osb_and_plugin_test/provision_timeout_test/provision_timeout_suite_test.go
test/osb_and_plugin_test/provision_timeout_test/provision_timeout_test.go

provision timeout

---

storage/postgres/query_builder_test.go
storage/postgres/where_clause_tree.go

fix for  fieldQuery and labelQuery contains operator

add sql filter to contains

---

api/api.go
api/osb/catalog_fetcher_test.go
test/operations_test/cascade_test/cascade_suite_test.go
test/operations_test/operations_test.go
test/service_instance_and_binding_test/service_binding_test/service_binding_test.go
test/service_instance_and_binding_test/service_instance_test/service_instance_test.go

Upgrade the osb version to 2.14 in order to support fetching a Service Instance and Service Binding.

upgrade osb version to 2.14

---

api/filters/shared_instance_update_filter.go
api/osb/instance_sharing_plugin.go
pkg/instance_sharing/types.go
pkg/types/service_plan_utils.go
pkg/util/errors.go
storage/interceptors/broker_create_catalog_interceptor.go
storage/interceptors/broker_update_catalog_interceptor.go
test/broker_test/broker_test.go
test/common/catalog.go
test/operations_test/cascade_test/cascade_suite_test.go
test/service_instance_and_binding_test/service_binding_test/service_binding_test.go
test/service_instance_and_binding_test/service_instance_test/service_instance_test.go

Renaming the key `supportInstanceSharing` to `supportsInstanceSharing`

supportInstanceSharing -> supportsInstanceSharing

---

api/common/sharing/utils.go
pkg/util/errors.go
test/service_instance_and_binding_test/service_instance_test/service_instance_test.go

Modifying the instance sharing error messages.

Instance sharing error messages

---

api/profile/controller.go
pkg/health/types.go
pkg/sm/sm.go

performance improvements
1. open pprof profile api end point
2. disable PlatformIndicator due to performance issue
3. improve performance of calculateIntegrity
* [X ] Refactoring

performance improvements

---

pkg/sm/sm.go

skip technical platforms for integrity calculation on SM startup

skip technical platforms for integrity calculation on sm startup

---

api/common/sharing/utils.go
storage/named_query.go
test/service_instance_and_binding_test/service_instance_test/service_instance_test.go

Instance Sharing selectors support non-case-sensitive queries.

Non case sensitive selectors

---

storage/named_query.go

reduce registration time of a service broker
improve db query to get last operation of a resource

performance improvement 

---

api/osb/osb_controller.go
api/osb/osb_controller_test.go
config/config.go
pkg/client/broker_client.go
pkg/client/broker_transport.go
pkg/httpclient/settings.go
pkg/httpclient/settings_test.go
storage/interceptors/smaap_service_instance_interceptor.go
test/broker_test/broker_test.go

* Monitoring  tls connections made from the service manager to brokers 
Adding logs

adding tls logs and validation

---

schemas/predefined_plans.go

Set the reference plan properties to support UI views.

update reference plan definition

---

api/filters/check_platform_suspended_filter.go
test/osb_and_plugin_test/plugin_test/platform_suspended_plugin_test.go

allow deletion for suspended platform

---

storage/interceptors/smaap_service_binding_interceptor.go
storage/interceptors/smaap_service_instance_interceptor.go

log when handling non smaap instances on smaap

---

api/filters/checkBrokerCredentials.go
pkg/types/credentials.go
pkg/types/service_broker.go
storage/postgres/broker.go
test/broker_test/broker_test.go

move sm_provided_tls_credentials to tls object

change sm provided credentials level

---

pkg/types/credentials.go

delete unnecessary marshal

---

api/base_controller.go
test/service_instance_and_binding_test/service_instance_test/service_instance_test.go

add labels on the entity before validate

---

sonar-project.properties

Add SonarQube default properties file

Feature  add sonarqube configuration

---

sonar-project.properties

coverage report should not include auto generated files and "fake" test files

Update sonarqube properties file

---

pkg/env/cf.go
storage/interfaces.go
storage/postgres/notificator.go
storage/postgres/storage.go
storage/postgres/storage_test.go

verify root ca postgres

---

storage/interfaces.go
storage/postgres/locker.go
storage/postgres/storage.go
test/rate_limiter_test/rate_limiter_test.go

skip ssl by configuration

---

operations/config.go
operations/maintainer.go
test/common/operation.go
test/operations_test/operations_test.go
test/service_instance_and_binding_test/service_instance_test/service_instance_test.go

Improve operation deletion performance
delete operations with batches

delete operations with batches

---

api/service_binding_controller.go
test/service_instance_and_binding_test/service_binding_test/service_binding_test.go

add patch binding labels support

---

api/filters/rate_limiter_filter.go

add tenant in rate limit exceeded error

log tenant in rate limit exceeded error

---

go.mod

Update crypto version

---

api/api.go
api/info/info_controller.go
test/service_instance_and_binding_test/context_signature/context_signature_test.go
test/service_instance_and_binding_test/context_signature/suit_test.go

support successor key

---

go.mod
go.sum

revert goland/crypto update

---

api/osb/context_signature_plugin.go
storage/interceptors/smaap_service_binding_interceptor.go
storage/interceptors/smaap_service_instance_interceptor.go
test/common/context_signature.go
test/service_instance_and_binding_test/context_signature/context_signature_test.go
test/service_instance_and_binding_test/context_signature/suit_test.go

avoid failing the request if sign fail

---

go.mod

update fasthttp version

---

api/osb/osb_controller.go

Add correlation id headers for logging and request tracing purposes
Add "X-Broker-API-Request-Identity" and "X-Correlation-ID" headers on requests to service brokers.

add correlation id header in osb requests to service brokers

---

go.mod

Increase version of fsnotify 1.4.9 -> 1.5.4
