cf/env.go, cf/env_test.go, config/config.go, main.go, server/server.go
Currently SM does not respect CF's PORT env variable and instead starts the process on a port of its own desire (defaults to 8080, picked up from application.yml). If CF picks a different port for the SM process, this leads to CF health check failure. 
This seems to have appeared after switching from running a docker container to using the go buildpack.
=> Respect PORT when running in CF

.travis.yml
The build should be faster.
Adding --vendor-only to speedup the dependency installation.
- [n/a] Initial implementation
- [n/a] Refactoring
- [n/a] Unit tests
N/A
=> Use vendor-only on dep install

api/osb/osb_controller.go, test/common/common.go, test/osb_test/osb_test.go
*When a broker is registered with path suffix. For example: http://broker.com/sm.
Normally calls should go to http://broker.com/sm/v2/catalog for getting the catalog.*
=> Fix: wrong path when broker has a url path suffix

Gopkg.lock, Gopkg.toml, api/broker/broker_controller.go, api/platform/platform_controller.go
satori/go.uuid is no longer maintained and it has critical bug which won't be fixed - generating uuids is not random. A fork is in place that fixes this bug while continuing with new features.
https://www.reddit.com/r/golang/comments/996iyv/comment/e4lq1s7/?st=JL5I55UC&sh=2ecaa671
https://github.com/satori/go.uuid/issues/73
=> Switch from satori/go.uuid

api/filters/logging_test.go, pkg/log/request.go, pkg/util/slice/strings.go
X-Request-ID is also taken as a correlation id - https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Common_non-standard_request_fields 
golang's `Header.Set` uses [CanonicalMIMEHeader](https://golang.org/pkg/net/textproto/#CanonicalMIMEHeaderKey) which changes the capitalisation of ID. Also per https://tools.ietf.org/html/rfc7230#section-3.2 header keys are case-insensitive.
=> Fix setting correlation id header

api/filters/authn/oauth/authenticator.go, api/filters/authn/oauth/authenticator_test.go
if Authorization header is passed and bearer token is used, it should not matter in what case is the key word "bearer"
=> Trim bearer prefix no matter the case

docs/install/cf-proxy.md, docs/install/k8s-proxy.md
Make it clearer to follow the installation guide to install service manager proxy to k8s and cf.
=> Adapt docu with missing information after following guide

api/http_handler.go, api/http_handler_test.go, application.yml, pkg/server/server.go
SM should be able to configure the maximum body request size and header sizes
Currently there is no easy way to test request headers size, as this requires to start real http.Server, rather than a httptest.Server. Tested it with Postman and it rejects request with large header values.
=> Limit request body size and header size with configuration

api/broker/broker_controller.go, test/broker_test/broker_test.go
Update broker updated the stored broker's credentials to an unencrypted version which caused consecutive update broker requests to fail ( the first one would succeed and each patch after that would fail)
=> Fix patch broker updating with unencrypted credentials

pkg/log/context.go, pkg/server/server.go, pkg/sm/sm.go, test/common/application.yml, test/common/test_context.go, test/osb_test/osb_test.go
This addresses a few issues with logging when executing API tests (tests located in /tests). This does not apply for the unit tests.
- Tests now only show sm logs when they fail
- Log level can now be changed in tests via the common/application.yml (which was not working before)
- Log level in tests is set to debug
- Only sm logs for the particular failing `It` will be shown
=> Improve logging during API tests execution

pkg/query/selection.go, pkg/query/selection_test.go
Currently label querying allows `duplicate label query keys` and disallows `duplicate field query keys` which is rather inconsistent. This PR disallows duplicate label querying. (e.x. labelQuery=key-op-val|key-op-val is disallowed and  labelQuery=key-op-val|key-op-val2  is not allowed)
=> Disallow duplicate label querying

api/api.go, api/info/info_controller.go, test/info_test/info_test.go
Some authorization servers like CF UAA have issues when client credentials are passed as basic auth.
See cloudfoundry/uaa#778
SM returns on the info endpoint a new property token_basic_auth (default true).
If token_basic_auth is false, client credentials should be sent in the body instead of in authorization header (basic auth).
=> Info endpoint returns token_basic_auth

pkg/util/api_test.go, pkg/util/errors.go, pkg/util/errors_test.go
When handing client errors, we don't want to propagate the client error to the api consumer but rather log it and return a general error
=> handle error from client response

api/broker/broker_controller.go, api/visibility/visibility_controller.go, pkg/query/selection.go, pkg/query/update.go, pkg/query/update_test.go, pkg/util/errors.go, storage/postgres/abstract.go, storage/postgres/labels.go, test/broker_test/broker_test.go, test/visibility_test/visibility_test.go
* small refactoring on labels
* when creating or updating a resource with labels, return 2xx instead of 409 if a label value is already present
* when creating or updating a resource with labels, return 2xx instead of 409 if a label is already present
* when creating or updating a resource with labels, return 2xx instead of 404 if a label is already deleted
* when creating or updating a resource with labels, return 2xx instead of 404 if a label value is already deleted
=> Adjust label errors

pkg/types/broker.go, test/broker_test/broker_test.go, test/common/common.go, test/delete_list.go, test/list.go
Broker API response now returns "service_brokers" instead of "brokers"
* Requires adoption in proxy-core
* Requires adoption in CLI
=> Broker API response now returns "service_brokers" instead of "brokers"

test/common/broker.go
Currently the test broker reads the request body in one of its middlewares and does not allow the subsequent handlers to use the body.
This PR addresses the issue.
=> Test Broker request body not usable

api/broker/broker_controller.go, test/broker_test/broker_test.go
Currently a broker may expose multiple service in its catalog where each service may contain the same set of plans. This PR fixes the issue where this is not allowed
=> Patch service broker with duplicate plans per service

api/platform/platform_controller.go, test/platform_test/platform_test.go
Currently when updating a platform the response body would contain credentials where the password would be messed up (because it's encrypted).
In reality, we have specified in the Service Manager specification that platform credentials will be returned only upon platform credentials. So we should not return then in any form for other APIs.
=> Omit platform credentials for Platform PATCH API response

storage/postgres/migrations/007_drop_broker_url_constraint.down.sql, storage/postgres/migrations/007_drop_broker_url_constraint.up.sql
Broker registrations should not be restricted to unique URLs. Unique names should be sufficient for now.
Added migration.
=> Drop Broker URL constraint

pkg/util/client.go, pkg/util/client_test.go
Currently send request util cannot be used for post/patch apis that require content-type header. A new util method is added to allow providing headers (this is also backward compatible as the go API of the old SendRequest method is not changed)
=> Add sending request with headers

test/broker_test/broker_test.go
When broker with 2 services and identical plans is updated (broker's catalog is not changed), Service Manager should not confuse these plans. This PR addresses this behavior with component test.
=> Add test for updating broker with 2 services and identical plans

Gopkg.lock, pkg/log/context.go, pkg/log/context_test.go
Caused by:
https://github.com/onrik/logrus/pull/10 line 42
https://github.com/sirupsen/logrus/blob/master/entry.go#L245
The logger's mutex must be shared between all logrus.Entry instances, so that the hooks firing is synced. Fix is to pass the same logger to every entry.
=> Race condition with new logrus version

cf/env_test.go
When STORAGE_URI env variable is set the test cf/env_test.go fails.
Solution is to unset the variable before the tests begin.
=> Fix cf/env_test when STORAGE.URI is set

application.yml, storage/interfaces.go, storage/postgres/abstract.go, storage/postgres/security.go, storage/postgres/storage.go
Currently, rows are not closed in multiple places.  
This results in connection exhaustion when decrypting credentials for more than 50 items at a time.
Tested on a local dockerized Postgres with max connections = 100. 
110 platforms in the database. On `List` the password is decrypted:
No call to list platforms passes, because for each platform, a new connection is opened to the database, but is not closed / released. So with any more than 50 platforms in the database, this call fails.
* 50 parallel requests. 
We get a spike of idle & total connections.
* 97 parallel requests. 
Sometimes  `sorry, too many clients already` which is expected, as the maximum number of connections is 100
Tried to perform the tests by starting a transaction to fetch the platforms & encryption key inside it. …
=> Release connection when working with rows

api/http_handler.go, pkg/web/filter.go
* Adds http.ResponseWriter to web.Request
* Allows to hijack the response writer from the request
* If response writer is hijacked, all content in the web.Response's Body is ignored (including headers). This will be the responsibility of the hijacker (web socket connection)
=> allow to hijack response writer from web request

test/common/common.go, test/common/test_context.go, test/osb_test/osb_test.go
https://github.com/Peripli/service-manager/issues/262
I'm trying to extend test framework to allow custom headers in the requests for creating platforms and brokers.
New parameter is added to functions that create platforms and brokers which may contain custom headers.
Use checklists as a means to represent the status of your Pull Request.
For example:
Not applicable.
Not applicable.
[1]: https://github.com/Peripli/service-manager/blob/master/CONTRIBUTING.md
=> Extend test framework

.gitignore
After running make some generated files appear as new files to git. These files should not be commited.
Add those files to .gitignore
=> Ignore make leftover files

api/notifications/notifications.go, cmd/smgen/api_type_template.go, pkg/types/notification_gen.go, pkg/types/platform_gen.go, pkg/types/servicebroker_gen.go, pkg/types/serviceoffering_gen.go, pkg/types/serviceplan_gen.go, pkg/types/visibility_gen.go, test/ws_notification_test/ws_notification_test.go
If there are no notifications in the db, SM returns last_notification_revision 0. Then the connection breaks for a long time so some notifications pass and are cleaned from the db. Then the proxy will try to reconnect with last_notification_revision 0. SM should return status 410 Gone. Otherwise the proxy may miss some notifications.
Now SM always return status 410 if last_notification_revision = 0.
Add more tests
Fix race condition when the same notification is sent on multiple ws connections
=> Fix handling with notification revision 0

api/base_controller.go, pkg/query/update.go, pkg/query/update_test.go, storage/interceptable_repository.go, storage/postgres/interfaces.go, storage/postgres/storage.go
Applying the label changes to the labels before handing them to the interceptor chains allows the interceptors to use the new objects labels and creating entitlements and visibilities. This fixes an issue in the internal update interceptors (sub-accounts, entitlements)
=> apply label updates to labels before triggering interceptors

pkg/server/server.go
The NewSettings function in the server package is never really used.
Better to just delete it so all our different settings stay consistent.
=> Remove unused NewSettings function in server package

api/api.go, api/base_controller.go, api/filters/patch_labels_only.go, api/service_offering_controller.go, api/service_plan_controller.go, pkg/query/update.go, pkg/query/update_test.go, storage/postgres/postgresfakes/fake_notification_storage.go, storage/postgres/secured_storage_test.go, storage/storagefakes/fake_secured_transactional_repository.go, test/broker_test/broker_test.go, test/list.go, test/platform_test/platform_test.go, test/service_offering_test/service_offering_test.go, test/service_plan_test/service_plan_test.go, test/test.go, test/visibility_test/visibility_test.go
Currently there is no way to add/remove labels on service offerings and service plans.
Introduces a patch API to service offerings and service plans apis that allows patching only the labels.
=> [Fixit] Allow patching labels of services and plans

config/config.go, config/config_test.go, main.go, pkg/env/cf.go, pkg/env/cf_test.go, pkg/env/env.go, pkg/log/context.go, pkg/sm/sm.go, storage/interfaces.go, storage/postgres/storage.go, storage/postgres/storage_test.go, storage/registry.go, test/common/test_context.go, test/sm_test/sm_test.go
Service Manager custom implementations most likely would require information regarding different base SM configuration properties. In this way, custom SM implementations can wrap the default SM configuration easier, only provide the default one to the SM Builder and not have the default configuration "encapsulated" inside the constructor of the SM Builder.
The `sm.New()` function now takes as final parameter a config instead of environment.
This PR also removes panicing inside some functions and delegating the error down to the `main()` functions.
=> Construct SMBuilder with config instead of environment

Gopkg.lock, pkg/env/env.go, pkg/env/env_test.go, pkg/env/helpers.go
There could be situations where slices are part of SM's configuration and corresponding pflags should be able to be created based on that.
Remove the restriction for slices.
For example:
=> Allow pflag creation for slices

test/notification_cleaner_test/notification_cleaner_test.go
Notification cleaner test was failing because of using Expect in async test. Eventually is used to fix the test.
=> Fix failing notification cleaner test

storage/postgres/interfaces.go, test/storage_test/storage_test.go
When entity (for example platform) is fetched directly from storage and it should not have any labels. The bug is that there are labels with empty key and empty value.
This empty labels are not returned by the REST API, because JSON encoder removes them when encoding the object.
This PR fixes the above described bug.
=> Do not return empty labels when no labels are present in database

storage/postgres/query_builder.go, storage/postgres/query_builder_test.go
Currently the delete query attempts to return labels. If we delete a visibility that has a one label called `org_id` and three values (org1,org2 and org3) the query will return one row containing the details about the visibility and the first deleted label value (org1). Then the created notification will include only one value (org1) in the payload for the label `org_id`  and the proxy will disable the service plan access for only this org and miss disabling for the other two.
There is no great benefit in trying to complicate the query further and try to return all deleted labels as deleting the resource will delete all labels linked to it anyway (unless we find some neat solution). 
Proposed solution with this PR is to revert to not returning information about labels when deleting a …
=> Fix deletion query building

api/filters/recovery.go, api/http_handler.go, api/notifications/ws_connection.go, api/osb/osb_controller.go, pkg/util/errors.go, pkg/util/errors_test.go
If an error occurs, the last log in the chain has no correlation id. 
This addresses this issue by adding context to the error handling and using the correlation id from the request
This helps troubleshooting because often the last log in the chain contains valuable information about the error and now it is difficult to find it
=> Add context to serve error logging

test/common/test_context.go
Some tests might require to provide a custom server listener, ex. in order to control on which port it is deployed and be able to construct accurate expectations.
Introduce a new `BuildWithListener` method for building `TestContext` structs with a predefined listener.
=>  Make test SM server listener replaceable

api/notifications/notifications.go, api/notifications/ws_connection.go, storage/postgres/notification_connection/connection.go, storage/postgres/notification_connection/notification_connectionfakes/fake_notification_connection.go, storage/postgres/notificator.go, storage/postgres/notificator_test.go
If only one proxy is connected to SM it should receive notifications.
When this proxy disconnects, SM calls Unlisted to postgres so that it does not receive unnecessary notifications. When a proxy reconnects again SM does not call listen again.
Always call unlisten/listen when proxy disconnects/connects. 
Also improve logging for these scenarios.
=> Fix postgres Listen not called in some cases

application.yml, config/config.go, pkg/httpclient/settings.go, pkg/httpclient/settings_test.go, pkg/sm/sm.go, test/broker_test/broker_test.go, test/common/application.yml, test/common/test_context.go, test/osb_test/osb_test.go
Currently osb calls do not have timeout. This could lead to out of memory if multiple calls hang to a broken broker.
Introduce timeout configurations for all outbound communication.
=> Add timeout for osb calls

pkg/log/context.go, pkg/log/context_test.go, pkg/log/formatter.go, pkg/log/formatter_test.go
This PR also enables Kibana log format in SB proxies.
Kibana log formatter reusable by SB proxies is needed.
Add kibana log formatter in SM, so it can be used by all dependent components including the SM.
=> Kibana formatter

pkg/log/context.go, pkg/types/notification.go, storage/interceptors/notifications_interceptor.go, storage/postgres/keystore_test.go, storage/postgres/migrations/20190816162000_notifications_corr_id.down.sql, storage/postgres/migrations/20190816162000_notifications_corr_id.up.sql, storage/postgres/notification.go
For better traceability, notifications should carry the correlation-id of the request that created the notification. This way a call to "register service broker" can be traced to the respective platform.
=> Store correlation id in notification

api/osb/osb_controller.go, test/common/application.yml, test/osb_test/osb_test.go
Sometimes it is hard to know whether the problem for certain OSB calls is because of the Service Manager or the broker itself. This change sends also the name of the broker and its response to the user.
=> Osb responses to include the broker name if an error occurs

api/base_controller.go, pkg/types/interfaces.go, test/broker_test/broker_test.go, test/delete_list.go, test/interceptors_test/interceptors_test.go, test/list.go, test/notification_test/notification_test.go, test/public_plans_interceptor_test/public_plans_test.go, test/service_offering_test/service_offering_test.go, test/service_plan_test/service_plan_test.go, test/visibility_test/visibility_test.go
All List operations must return the same response scheme
```
{
"num_items": <the number of items returned>,
"items": [
{ ... }
]
}
```
=> Unify response for list operations

api/api.go, api/base_controller.go, api/filters/paging.go, api/filters/paging_test.go, pkg/query/selection.go, pkg/query/selection_test.go, storage/encrypting_repository.go, storage/interceptable_repository.go, storage/interfaces.go, storage/postgres/query_builder.go, storage/postgres/query_builder_test.go, storage/postgres/storage.go, storage/storagefakes/fake_storage.go, test/list.go
SM list API must handle the max_items query parameter to determine the maximum number of items to return.
This max_items parameter must not be greater than an internally configured value.
Parameter max_items introduces which means maximum number of items to return in the response.If the client sets max_items to 0, it is assumed that the client is only interested in the total number of items.
=> Support max_items query parameter

deployment/cf/manifest.yml, deployment/k8s/charts/service-manager/Chart.yaml, deployment/k8s/charts/service-manager/values.yaml
The deployment descriptors (helm charts and cf manifest) were outdated. These PR updates them
=> Fix deployment descriptors

pkg/util/api_test.go, pkg/util/client.go, pkg/util/list.go, pkg/util/list_test.go, pkg/util/util_suite_test.go, test/common/common.go
Common client utility for iterating through pages
Two usages are supported:
* iterator - load one page at a time, do not keep all the items in memory
* load all items - load all the items in memory by iterating through all the pages
=> Paging client

Gopkg.lock, api/api.go, api/notifications/notification_controller.go, api/notifications/notifications.go, api/notifications/ws_connection.go, pkg/sm/sm.go, pkg/ws/settings.go, storage/postgres/notificator.go, storage/postgres/notificator_test.go, test/ws_notification_test/ws_notification_test.go
Currently managing platform status is done when WS connection is established and terminated with a platform (proxy agent). This leads to health check problems during B/G deployment when Service Manager runs on multiple nodes.
Stop managing platform statuses on WS connection establishment/termination and instead manage statuses during ping/pong flow.
=> Manage platform status during ping/pong flow

storage/postgres/notification_connection.go, storage/postgres/notificator.go
The following error occurs when connecting to postgres for notifications: 
level=error msg="DB connection for notifications closed" component="postgres/notificator.go:108" correlation_id=- error="pq: SSL is not enabled on the server"
Allow settings the connection to be without ssl if configured as such.
=> Allow settings ssl when connecting with notificator

Gopkg.lock, api/base_controller.go, storage/interceptable_repository.go, storage/interceptors_create.go, storage/postgres/storage.go
The implementation of _InterceptableTransactionalRepository_ is similar to _interceptableRepository_, but it still differed in some subtle ways, like introducing intermediary structs like * finalCreateObjectInterceptor*. This PR eliminates the intermediary structs and tries to make both repository implementations more similar.
Also added some docs to some package and public structs as I thought it would be beneficial for later on.
Refactor _InterceptableTransactionalRepository_ to be similar to _interceptableRepository_ by removing unnecessary code.
For example:
=> Trim down interceptable repository code

pkg/web/filter.go, pkg/web/matcher_test.go
With log elevel on _debug_ a typical OSB request log looks likes this:
```
October 17th 2019, 11:27:44.627	service-manager-new	5549006d-b6e5-4103-7122-8edfbd850324	DEBUG	web/filter.go:176	Exiting Filter: AuthAuditLogFilter
October 17th 2019, 11:27:44.627	service-manager-new	5549006d-b6e5-4103-7122-8edfbd850324	DEBUG	auditlog/common.go:76	User context contains a name, considering basic authentication
October 17th 2019, 11:27:44.627	service-manager-new	5549006d-b6e5-4103-7122-8edfbd850324	DEBUG	web/filter.go:176	Exiting Filter: DELETE-BasicAuthzFilter@/v1/osb/**
October 17th 2019, 11:27:44.627	service-manager-new	5549006d-b6e5-4103-7122-8edfbd850324	DEBUG	web/filter.go:176	Exiting Filter: BasicAuthnFilter
October 17th 2019, 11:27:44.627	service-manager-new …
```
=> Remove too verbose filter logs

pkg/query/selection.go, pkg/query/selection_test.go, storage/postgres/query_builder_test.go, storage/postgres/where_clause_tree.go
If the second operand to `in` operator is an empty array, it used to panic
```
runtime error: index out of range
goroutine 55 [running]:
runtime/debug.Stack(0x1ab5e62, 0xc00073b6f0, 0x100e4e8)
/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.corp/SvcManager/sm-sap/vendor/github.com/Peripli/service-manager/api/filters.NewRecoveryMiddleware.func1.1.1(0xc000404b00, 0x1c2f6e0, 0xc0006a4000)
/Users/user/go/src/github.corp/SvcManager/sm-sap/vendor/github.com/Peripli/service-manager/api/filters/recovery.go:23 +0xe4
panic(0x1991ce0, 0x2476130)
/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.corp/SvcManager/sm-sap/vendor/github.com/Peripli/service-manager/storage/postgres.buildRightOp(0x1c33a20, 0x1c039a0, …
```
=> Fix panic: index out of range

api/api.go, api/service_instance_controller.go, pkg/web/routes.go
https://github.com/Peripli/service-manager/pull/353
Allows fetching existing Service Instances. Authentication/Authorization is not included.
For example:
https://github.com/Peripli/service-manager/pull/351
=> Service Instance GET/LIST APIs

api/api.go, pkg/sm/sm.go, storage/interceptors/service_instance_create_interceptor.go, test/service_instance_test/service_instance_test.go
Service Manager needs to label all instances with the tenant in which it is created.
To do this, there needs to be an AroundTx interceptor that adds a <tenant_identifier> label to the service instance. The value of the <tenant_identifier> label can be obtained from the context field in the service instance.
=> Introduce Service Instance labelling interceptor

api/filters/basic_authentication.go, api/filters/oidc_authentication.go, api/filters/tenant_filter.go, api/filters/tenant_filter_test.go, pkg/security/filters/required_authn.go, test/auth_test/auth_test.go, test/service_instance_test/service_instance_test.go
The service instance api should be used only by authenticated users.
Extend the existing authentication mechanism by adding the service instance url.
Use checklists as a means to represent the status of your Pull Request.
For example:
=> Add authentication for service instance endpoint

pkg/types/service_broker.go, pkg/util/api.go, test/broker_test/broker_test.go
Sometimes broker registrations contain names longer than the DB max char limit (255) for that field, which results in 500 Internal Server error.
The `Validate()` method of the Service Broker entity ensures the broker name is lesser than 255 symbols. If it is bigger, 400 Bad Request with appropriate error message is returned.
=> Forbid registering brokers with long names

api/base_controller.go, api/osb/store_instances_plugin.go, pkg/web/api.go, storage/encrypting_repository.go, storage/encrypting_repository_test.go, storage/interceptable_repository.go, storage/interceptable_repository_test.go, storage/interceptors/broker_delete_catalog_interceptor.go, storage/interceptors/broker_public_plans_interceptor.go, storage/interceptors/broker_update_catalog_interceptor.go, storage/interceptors/notifications_interceptor.go, storage/interceptors_delete.go, storage/interfaces.go, storage/notification_cleaner.go, storage/notification_cleaner_test.go, storage/postgres/query_builder.go, storage/postgres/query_builder_test.go, storage/postgres/storage.go, storage/storagefakes/fake_storage.go, test/broker_test/broker_test.go, test/common/common.go, test/interceptors_test/interceptors_test.go, test/notification_cleaner_test/notification_cleaner_test.go, test/osb_test/poll_instance_last_operation_test.go, test/query_test/query_test.go, test/ws_notification_test/ws_notification_test.go
Notifications payload is often large and loading deleted notifications inmemory is not necessary. In general in most places we delete stuff, loading it inmemory is not needed. The PR addresses these points
=> Delete notifications to not return result

PULL_REQUEST_TEMPLATE.md, storage/postgres/keystore_test.go, storage/postgres/migrations/20191214124420_increase_operations_external_id_length.down.sql, storage/postgres/migrations/20191214124420_increase_operations_external_id_length.up.sql
Some brokers returns operation strings longer than 100 symbols (the current cap). Also OSB spec states that 10 000 characters should be the max: https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#body-4
Migrations added.
We still don't have an operations maintainer. Currently operations are never deleted. Increasing the size of an operation record will shorten the time until we eventually fill up the DB.
So it's important to introduce an operations maintainer ASAP.
=> Increase Operation external_id length

pkg/types/interfaces.go, storage/interceptors/broker_notifications_interceptor.go, storage/interceptors/notifications_interceptor.go, storage/interceptors/visibility_notifications_interceptor.go
Deleting a visibility creates the corresponding notification. The notification requires also additional data, so for each visibility SM loads its plan, service offering and broker - 3 db calls for each visibility.
In case multiple visibilities are deleted in one operation this produces a lot of db calls and the operation may take 10+ seconds.
Now the additional data is loaded for all deleted visibilities with just 3 db calls independent of the visibility count.
=> Batch fetching details for visibility notifications

api/osb/store_instances_plugin.go, test/osb_test/poll_instance_last_operation_test.go
As per OSB spec a response to a last operation call can return 410 Gone: https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#response-1
In the case of an async delete operation, this has to be interpreted as the instances has been deleted in the original service broker.
Currently we do not handle this scenario as we're always expecting a 200 OK response: https://github.com/Peripli/service-manager/blob/8598d3c656897e687b8b443ef256839e0792f42a/api/osb/store_instances_plugin.go#L354
The consequences are that we have orphan instances in our DB, which furthermore complicate things as those instances block the deletion(or catalog update) of the corresponding service broker in SM. For such cases, we have to go directly in the DB and delete those instances (until we have a …
=> Handle 410 Gone on Last Operation requests

operations/jobs.go, operations/maintainer.go, pkg/types/operation.go, storage/postgres/keystore_test.go, storage/postgres/migrations/20200101212700_operations_claimed_at.down.sql, storage/postgres/migrations/20200101212700_operations_claimed_at.up.sql, storage/postgres/operation.go
This PR was created in the hopes to ease the discussion process of whether we need such a change. Until the team has agreed upon such an approach, this change only serves as a reference implementation.
The operation maintainer currently updates operations older than job_timeout to failed. It does so by making a diff between the current time and the created_at timestamp of the operation, but this is somewhat flawed - it's possible for an operation to be in the "job queue" and may have not been claimed at. Such operations are not stuck or orphans, they are just waiting for their turn to come when they're executed.
This PR proposes an introduction of a `claimed_at` property to operation entities, which will be set first thing when an operation (job) execution starts running.
This way the …
=> Introduce ClaimedAt operations property [async engine story]

pkg/types/interfaces.go, pkg/types/notification.go, pkg/types/operation.go, pkg/types/platform.go, pkg/types/service_broker.go, pkg/types/service_instance.go, pkg/types/service_offering.go, pkg/types/service_plan.go, pkg/types/types_test.go, pkg/types/visibility.go, storage/interceptors/notifications_interceptor.go, storage/postgres/scheme_test.go, test/notification_test/notification_test.go
In certain cases - there is no need to send visibility's labels such as:
1) Update visibility
1.1) when platform id and plan id is not changes - then only label changes are enough
1.2) when plan id is changed, then old visibility's labels are not needed, as we know we should delete all visibilities in the platform. Only the new visibility's labels are needed
1.3) when platform id is changed, then no update notification should be send, because only delete and create notifications are needed. Currently this cannot be avoided because tests will fail for broker notifications.
Overall result is: Approximately 2x times smaller notification size, because old visibility will never have labels. Sometimes the size will be even smaller, when no visibility labels will be sent at all, as only label …
=> Remove visibility notification labels

api/osb/check_visibility_plugin.go, test/osb_test/provision_test.go
If an OSB request for provision from Cloud Foundry has no context we return 500 with unhelpful description.
Return 400 with some description of the problem.
=> fix 500 on provision without context

storage/postgres/abstract.go
Sometimes the error info in the log is not enough, e.g.
```
HTTPError: found conflicting Platform
```
Now we log also the original postgres error, e.g.
```
duplicate key value violates unique constraint "platforms_name_key": Key (name)=(cf1) already exists.
```
=> Log original SQL error

api/osb/store_instances_plugin.go, pkg/types/service_instance.go, pkg/types/types_test.go, storage/postgres/keystore_test.go, storage/postgres/migrations/20200114101000_dashboard_url.down.sql, storage/postgres/migrations/20200114101000_dashboard_url.up.sql, storage/postgres/service_instance.go, test/testutil/service_instance/service_instances.go
The dashboard_url property is a top-level one which should be returned when fetching instances.
=> Persist dashboard_url for Service Instances

api/osb/check_instance_owner_plugin.go, api/osb/check_platform_id_plugin.go, api/osb/check_visibility_plugin.go
In case the service plan is not visible, service provisioning fails and we could see only this error in the log
```
HTTPError: could not find such types.ServicePlan
```
The actual reason was not clear.
Log explicitly that the plan is not visible.
=> Log error when no plan visibility is found

pkg/sm/security_builder.go, pkg/sm/sm.go, pkg/web/dynamic_matching_filter.go
Security builder was coupled with Service Manager Builder which made it impossible to adapt in the agents. Now security builder needs only dynamic filters in order to be used from the agents
=> Decouple sec builder from sm builder

storage/postgres/keystore_test.go, storage/postgres/migrations/20200116204800_dashboard_url_text.down.sql, storage/postgres/migrations/20200116204800_dashboard_url_text.up.sql, storage/postgres/service_instance.go, test/service_instance_test/service_instance_test.go
Service instance dashboard url is serialized from db into string.
There are some cases where this is actually null in the database (after db migration of existing service instances).
Therefore NullString should be used.
=> Fix instance dashboard url serialization

api/filters/check_instance_visibility_filter.go, test/service_binding_test/service_binding_test.go, test/service_instance_test/service_instance_test.go, test/test.go
- When plan has public SM visibility, one should be able to create instances
- When plan does not have any visibility and OAuth without tenant is used, one should not be able to create instances
=> Allow to create instances if there is public visibility for the plan

api/api.go, api/filters/checkBrokerCredentials.go, test/broker_test/broker_test.go
There may be cases when a user updates an existing service broker and provides only URL without the credentials, thus getting the real credentials of the broker.
Introduce checkBrokerCredentials filter.
=> Add checkBrokerCredentials filter

api/filters/visibility_filtering_middleware.go, api/healthcheck/platform_indicator.go, pkg/sm/sm.go, test/healthcheck_test/healthcheck_test.go
Wasn't adapted with the initial introduction of the SM platform.
=> Exclude SM platform from health check platform indicators

api/filters/service_binding_strip_filter.go, api/filters/service_instance_strip_filter.go, test/broker_test/broker_test.go, test/delete.go, test/operations_test/operations_test.go, test/patch.go, test/service_binding_test/service_binding_test.go, test/service_instance_test/service_instance_test.go, test/test.go
Clients should not specify IDs as this could risk data integrity and also could cause problems when storing instances/bindings from other platforms.
=> Forbid setting Instance/Binding ID from client-side

api/osb/check_visibility_plugin.go
If a client tries to access a plan that is not visible in the current context, he gets the error
`could not find such service plan`
which is confusing
Now we return error
`service plan not found or not accessible`
which describes better the reason
=> Return better message when plan is not visible

docs/development/logging.md
No clear guidelines what and how to log in the code.
Different approaches used in different parts of the code.
Developers are often confused which log level to use.
Define logging guidelines as part of development documentation.
=> Add logging guidelines

api/api.go, api/extensions/security/authn.go, api/filters/oidc_authentication.go, api/profile/controller.go, pkg/web/routes.go, test/auth_test/auth_test.go, test/common/common.go, test/profile_test/profile_test.go
Sometimes SM consumes lots of memory but it is not possible tell what exactly occupies most of the heap.
Expose pprof profiles on /v1/profile endpoint
* /v1/profile/goroutine
* /v1/profile/threadcreate
* /v1/profile/heap
* /v1/profile/allocs
* /v1/profile/block
* /v1/profile/mutex
See https://golang.org/pkg/net/http/pprof/
Once fetched these profiles can be analysed with `go tool pprof`.
The profiles above should not have significant impact on performance and should be safe to use in production, see
* https://github.com/golang/go/wiki/Performance
* https://groups.google.com/forum/#!topic/golang-nuts/e6lB8ENbIw8
=> Add endpoint to fetch pprof profiles

api/api.go, api/base_controller.go, api/service_binding_controller.go, api/service_instance_controller.go, test/service_instance_test/service_instance_test.go
As newly introduced APIs which might take longer than normal these should be Async by default.
=> Instance & Binding APIs Async by default

pkg/security/http/authz/oauth_scopes.go, pkg/security/http/authz/oauth_scopes_test.go
In some cases filters/interceptors need to know if a request has a specific scope, regardless of the request access level. At the moment there is no API for checking that. 
the new utility function in the authz package provides simple API for checking if a request user has a specific scope, abstracting the actual scope retrieval from the token.
=> Authz has scope

test/common/oauth_server.go
Integration tests related to the auth server are not flexible enough and if you want, for example, to check the request body, you will have to stop the running auth server and replace it with one that suits your needs.
With Gorilla mux we can add middlewares on the fly for the endpoints we want. In order to do that, the router should be exported.
=> Use gorilla mux in test OAuth server

storage/postgres/query_builder.go, storage/postgres/query_builder_test.go, storage/postgres/where_clause_tree.go, test/delete_list.go, test/list.go
Intersect all label queries instead of using `OR`.
Scenario:
* color = red
* user = my_user
* color = red
* user = your_user
If you want the `red` entities for `my_user` you'll execute `labelQuery=color eq 'red' and user eq 'my_user'`.  
Using `OR` this will return both entities.
=> Fix label queries

pkg/sm/sm.go, storage/interceptors/unique_binding_names_iterceptor.go, storage/interceptors/unique_instance_names_iterceptor.go, test/service_binding_test/service_binding_test.go, test/service_instance_test/service_instance_test.go, test/test.go
This constraint is currently done with interceptors but this might not work in some cases.
It should be done as a DB constraint.
=> Unique constraint for instance and binding names

api/osb/catalog_fetcher.go, test/broker_test/broker_test.go
We have error like this:
```
error fetching catalog for broker with name test-service-broker-tenant1: request GET https://test-service-broker.cfapps.stagingsc7.hanavlab.ondemand.com/v2/catalog failed: StatusCode: 404 Body: error reading response body: http: read on closed response body
```
which is misleading because actually we don't have problem reading response body
=> Reorder error handling for catalog fetcher

pkg/security/authenticators/basic_authentication.go, pkg/security/authenticators/basic_authentication_test.go, pkg/security/authenticators/oidc_authenticator.go, pkg/security/authenticators/oidc_authenticator_test.go, pkg/security/filters/middlewares/authentication.go, pkg/security/http/auth.go, pkg/security/http/authn/or_authenticator.go, pkg/security/http/httpfakes/fake_authenticator.go
There are instances where an Authenticator needs to parse for some value in the request path or something similar. Using web.Request eases this process.
=> Accept web.Request instead of http.Request in Authenticator interface

api/api.go, api/filters/supported_encodings_filter.go, test/osb_test/bind_test.go, test/osb_test/osb_suite_test.go
The Accept-Encoding field is used in an HTTP request to indicate which encodings are accepted in a response message to the request. This field is used to specify the values of gzip, deflate, compress and identity. A value of identity indicates that the data must not be compressed. A wildcard of * indicates that any encoding is accepted. The Accept-Encoding field can also be empty, indicating that no encoding is accepted. SM needs to support the handling of broker responses when the Accept-Encoding header is present and provided by the OSB clients as svcat.
Approach
The proposed changes add an Accept-Encoding header filter for OSB calls and filters out the Accept-Encoding header incase the request encoding is not supported
=> Proxy only sm supported encodings in OSB calls

Gopkg.lock, operations/maintainer.go, storage/interceptors/unique_binding_names_iterceptor.go, storage/interceptors/unique_instance_names_iterceptor.go, test/service_binding_test/service_binding_test.go, test/service_instance_test/service_instance_test.go, test/test.go
Rescheduling of CREATE/UPDATE operation by maintainer fails for instance/binding resources due to unique constraint violation as the interceptors enforcing uniqueness of instance/binding names find the instance/binding resources in SM DB (they are with ready=false) when trying to reschedule the operation.
This change tweaks the two uniqueness interceptors, but also more importantly enables the previously disabled maintainer tests (which test the rescheduling mechanism), which had been previously failing remotely on Travis. Due to those tests having been disabled we weren't able to detect the rescheduling bug when the unique instance/binding name interceptors were initially introduced.
=> Fix Rescheduling of Instance/Binding operations

api/base_controller.go
When attaching last operation to entity, no need for criteria from context, because it contains some criterias, not related to the operation entity
=> Fix attach last operation

storage/interceptors/broker_update_catalog_interceptor.go, test/broker_test/broker_test.go
Brokers could have their service and plan catalog IDs updated. Currently SM doesn't allow this because when inserting the new offering/planas there will be duplicate (broker_id, service_offering_name) and (service_offering_id, name) pairs which violates the unique constraint in the DB.
Ensure that the old offering/plan is deleted before trying to create the new one.
=> Allow Broker Catalog ID updates

api/base_controller.go
When listing objects different from brokers or platforms we get many messages like these in the log
```
Mar 18, 2020 @ 09:33:37.786	service-manager-new	21f21e3f-b7e2-446e-5b32-a7322d4dfecb	DEBUG	api/base_controller.go:502	Object of type /v1/service_plans with id 0cfba1f9-71fb-4389-831a-e55dd781dbbf is not secured, so no credentials are cleaned up on response
Mar 18, 2020 @ 09:33:37.786	service-manager-new	21f21e3f-b7e2-446e-5b32-a7322d4dfecb	DEBUG	api/base_controller.go:502	Object of type /v1/service_plans with id 74441f5b-44c5-4b99-97ee-8ae04ab77edd is not secured, so no credentials are cleaned up on response
Mar 18, 2020 @ 09:33:37.786	service-manager-new	21f21e3f-b7e2-446e-5b32-a7322d4dfecb	DEBUG	api/base_controller.go:502	Object of type /v1/service_plans with id …
```
=> Remove unnecessary log message

api/osb/catalog_fetcher.go, application.yml, pkg/httpclient/settings.go, storage/interceptable_repository.go, test/broker_test/broker_test.go, test/common/application.yml, test/common/test_context.go, test/configuration_test/configuration_test.go, test/osb_test/osb_suite_test.go
There are a few different aspects of these timeouts:
1. OSB calls via the /v1/osb API of Service Manager:
- Calls for get catalog are done via CatalogFetcher which uses the default http client which was not configured.
- Calls for all other requests are done via reverse proxy, which does not know when it should cancel the request, because the context is not cancelled on server.request_timeout. The only time it will time out is when the headers are not yet received. But if there is a "bad broker" which has returned headers, but is streaming the response very slowly, we will wait for the response forever. This can be fixed with something like [http.TimeoutHandler](https://golang.org/pkg/net/http/#TimeoutHandler). There is a branch with implementation: …
=> Configure default http client timeout

test/broker_test/broker_test.go, test/common/application.yml, test/configuration_test/configuration_test.go
Tests are failing sporadically on Travis for the operations maintainer. So increase the timeouts that they should not fail because of timeouts
=> Adjust http client test timeouts

Gopkg.lock, api/credentials_controller.go, test/osb_test/catalog_test.go
Unlike CF installations, K8S clusters are very volatile environments and it's easier to delete broker resources there. In case a broker is deleted in K8S directly (or CF for that matter), the broker record and its broker platform credentials will still exist in SM. And whenever the K8S agent retriggers full resync it would fail to register the broker back in the platform as it would try to essentially rotate the broker platform credentials - something we do not allow. We only allow full resync to initially set broker platform credentials, but now we will allow this rotation for K8S platforms,
Make broker platform credentials controller less restrictive.
=> Allow Broker Platform Credential Rotation during full resync in K8S platforms

pkg/web/api.go, pkg/web/api_test.go
When we want to register one plugin after another, the plugins are decomposed and their filters are ordered with respect to the implemented plugin interfaces.
Let's say we have three plugins: `First`, `Second` and `Third`.
`First` implements `Provisioner`, `InstanceUpdater` and `Deprovisioner`
`Second` implements only `Provisioner`
`Third` implements `Provisioner` and `Deprovisioner`. 
Currently, if we want to register the plugins as `First`, `Second` and then `Third` using the `RegisterPluginsBefore` method, their filters will have the following order:
- `First:Provision`
- `Second:Provision`
- `Third:Provision`
- `Third:Deprovision`
- `First:InstanceUpdater`
- `First:Deprovision`
This PR changes the ordering logic as it places all filters that belong to a plugin one after another, and …
=> Change filter order of plugins

api/base_controller.go, test/broker_test/broker_test.go, test/notification_test/notification_test.go
Attach last operation to the resource returned by PATCH and POST request for better and consistent experience with the CLI and API
=> Attach last operation to the resource on PATCH and POST

storage/postgres/storage.go, test/common/application.yml, test/configuration_test/configuration_test.go, test/visibility_test/visibility_test.go
pq has a limit of 65535 parameters, see https://github.com/lib/pq/blob/master/conn.go#L1282
now we insert labels in batches to avoid this limit
=> Insert labels in batches to avoid pq param limit

Gopkg.lock, api/api.go, api/api_test.go, api/filters/check_instance_transfer_filter.go, api/filters/platform_id_instance_validation_filter.go, storage/interceptors/smaap_service_instance_interceptor.go, test/common/test_context.go, test/osb_test/poll_instance_last_operation_test.go, test/security_test/security_test.go, test/service_instance_test/service_instance_test.go, test/storage_test/storage_test.go
The functionality if deleting instances across platforms requires storing bindings in SMDB as a prerequisite
=> Add flag to transfer API/disable delete across platforms

operations/config.go, operations/maintainer.go, operations/scheduler.go, test/configuration_test/configuration_test.go, test/operations_test/operations_test.go, test/service_binding_test/service_binding_test.go, test/service_instance_test/service_instance_test.go
* fix logging and missing correlation ids when maintainer schedules an operation
* fix namings of maintainer functors
* fix maintainer setting deletion scheduled on stuck updates
* fix maintainer trying to do orphan mitigation after a stuck update operation has been marked as failed
* fix scheduler trying to create a new operation when invoked by maintainer even though one already exists (when maintainer reschedules an operation which is not the last operation for this resource because several hours have passed and newer operations have appeared after the one that is being rescheduled)
=> Fixes in maintainer

api/osb/osb_controller.go, storage/interceptors/smaap_service_instance_interceptor.go, test/broker_test/broker_test.go, test/common/broker.go, test/common/test_context.go, test/osb_test/provision_test.go, test/service_instance_test/service_instance_test.go
Do not require basic credentials if broker supports tls when doing provision requests.
=> [FIX] Do not require basic credentials, when using tls

pkg/types/service_plan.go, test/broker_test/broker_test.go
https://jtrack.wdf.sap.corp/browse/NGPBUG-114921
SM accepted catalog with empty plan's description while CC doesn't.
They should be aligned. So this fix validated that a description exists
If you use third party code with your contribution such as, components, libraries, or snippets make sure to mention that.
Make sure that your contribution complies with our …
=> add validation to plan description (should not be empty)

.dockerignore
The .pipeline folder keep information needed only for CI/CD automation. Not related to project functionality or structure. Such files need to be ignored and not stored in repository. 
Adding folder to .gitignore
=> Add .pipeline to .gitignore

pkg/log/request.go
`X-CorrelationID` (with a single dash) is the correct header to set on outbound requests
=> Prefer X-CorrelationID header over X-Correlation-ID

pkg/types/service_plan.go, pkg/types/service_plan_utils.go, storage/service_plans/resolver.go, test/broker_test/broker_test.go, test/public_plans_interceptor_test/public_plans_test.go
In some cases a service plan must not be visible on a specific platform, e.g. to avoid name conflicts with locally-registered brokers on that platform. 
This change introduces a new property that can be added in a plan's catalog metadata: `excludedPlatformNames`. If set on a plan, this plan will not be visible on platforms with names specified in the property value.
=> Excluded platform names

.travis.yml, Makefile
After merging https://github.com/Peripli/service-manager/pull/520 we experience unstable stages in Travis. It happens because all stages use the same profile.cov file (coverage file). One stage can delete another stage profile.cov file and cause it to fail with error "Error parsing coverage: open profile.cov: no such file or directory"
To fix the issue, we simply use 5 different profile.cov files:
profile-unit.cov
profile-int-broker.cov
profile-int-osb-and-plugin.cov
profile-int-service-instance-and-bindings.cov
profile-int-other.cov
=> fix unstable tests executions

pkg/types/service_offering.go
null plans array is always returned for service_offerings, this might lead clients to assume there are no plans for the service.
=> omit empty 'plans' JSON field in service_offerings responses

pkg/security/http/authz/clientid_suffix_authorizer.go, pkg/sm/security_builder.go, test/security_test/security_test.go
In some cases it is required to support multiple trusted client ID suffixes in the authz layer.
Enhance the ClientIDSuffixAuthorizer and the security builder to support an array of allowed suffixes
=> Authz - Support multiple trusted client ID suffixes

api/osb/osb_store_plugin.go
When creating a binding on instance in k8s, the binding name is not enhanced on the context which is sent to SM.
SM verifies that a binding name exists, and if not it uses the binding Id as the binding name.
The current code the instance Id was used instead of the binding Id.
=> when there is no binding name use binding Id

application.yml, deployment/k8s/charts/service-manager/values.yaml, storage/interfaces.go, storage/postgres/storage.go, test/configuration_test/configuration_test.go
Go Postgres driver for database (github.com/lib/pq) does not have any default upper-bound on the connections pool size.
The default is 0 (unlimited). It is important to set MaxOpenConns
https://golang.org/pkg/database/sql/#DB.SetMaxOpenConns
Otherwise under certain circumstances it may lead to connections rate increasing exponentially, exhausting the connections, and as a result the driver can bring the database into a critical state.
=> setting maximum number of open connections to the database

.travis.yml, Makefile, api/base_controller.go, api/service_instance_controller.go, operations/scheduler.go, pkg/types/operartion_utils.go, pkg/types/operation.go, storage/interceptors/smaap_service_binding_interceptor.go, storage/interceptors/smaap_service_instance_interceptor.go, storage/postgres/migrations/20200708749000_operations_context.up.sql, storage/postgres/migrations/20200708749000_operations_is_context.down.sql, test/common/operation.go, test/operations_test/cascade_test/cascade_suite_test.go, test/service_instance_and_binding_test/service_binding_test/service_binding_test.go, test/service_instance_and_binding_test/service_instance_test/service_instance_test.go
For instance and binding management APIs, we would like to return the actual broker response, in cases where the client does not specify the async mode.
In case a client does not specify an expected response mode via the async=true/false query param.
Service Manager will attempt to fulfill a synchronize request to provision or de-provision a resource.
1. If the service broker response requires polling the response to the client will be async.
2. If the service broker response does not require polling, the client will get the broker response instantly 
3. In case of any errors returned by the service broker before polling has started, those will be instantly sent back to the client
Support is added to POST, PUT methods
=> Lifecycle addon v2

storage/interceptors/smaap_service_binding_interceptor.go, storage/interceptors/smaap_service_instance_interceptor.go
When create instance/binding failed we want to delete it from DB in case it Sync.
Changes:
Deleting using RawRepository instead of InterceptableTransactionalRepository , To prevent unnecessary running of interceptors
=> using rawrepository when deleting service instance/binding

storage/interceptors/broker_update_catalog_interceptor.go
Allow interceptors configured after the broker_update_catalog_interceptor to obtain the original reference to services and plans 
Use newObj instead of the updated_broker object
* [x ] Refactoring
=> pass newObj configured services & plans to interceptors after broker update catalog

api/api.go, api/filters/brokers_filter_by_visibility.go, api/filters/helpers.go, test/broker_test/broker_test.go, test/common/test_context.go, test/security_test/security_test.go
Brokers are not filtered when using platform basic credentials, this exposes tenant-owned brokers to other tenants. This change filters them based on visibilities of the broker plans, as it is done for service offerings.
=> filter brokers by visibilities in agent calls

storage/postgres/keystore_test.go, storage/postgres/locker_test.go, storage/postgres/migrations/20201005251500_notifications_revision_index.down.sql, storage/postgres/migrations/20201005251500_notifications_revision_index.up.sql
When notifications table grow large the queries for notification by revision issued by agents take too long, this index should improve the DB lookup times in this flow.
=> add index on notifications revision

application.yml, pkg/sm/sm.go, storage/interceptors/broker_notifications_interceptor.go, storage/service_plans/resolver.go, test/notification_test/notification_test.go
Broker notifications (CREATE/UPDATE/DELETE) are sent to all agents according to supportedPlatforms only. In case multi-tenancy is enabled, this leads to notifications about tenant-scoped brokers being sent to different tenant's platform. This is a breach to the tenant isolation. 
This change filters out platforms owned by other tenants in case of operations on a tenant-scoped broker.
=> Fix cross tenant notifications

storage/interceptors/broker_notifications_interceptor.go, storage/service_plans/resolver.go, test/common/test_context.go, test/interceptors_test/interceptors_test.go, test/notification_test/notification_test.go
Notifications are created for platforms that were registered but never connected. Those platforms will anyways do a full resync upon their first connection, so there is no point in storing those notifications.
This change skips those platforms during the broker notification flows, so no unneeded notification are created in this flow.
=> do not notify platforms that were never active

api/filters/checkBrokerCredentials.go, test/broker_test/broker_test.go
When updating broker_url we want to validate credentials were passed. Currently the filter validates only basic, adding tls as well.
=> add tls to CheckBrokerCredentialsFilter

api/filters/brokers_filter_by_visibility.go, api/filters/helpers.go, api/filters/plans_filter_by_visibility.go, api/filters/services_filter_by_visibility.go, api/osb/catalog_filter_by_visibility_plugin.go
Improve sm performance by reducing the amount of data that is fetched from the labels table and sent to the service manager app.
- Use repository.Count instead of repository.List(ctx, types.VisibilityType,etc..) when ever possible
- Use repository.ListNoLabels instead of repository.List when ever possible
=> improve service manager label list related scenarios

storage/interceptors/broker_public_plans_interceptor.go, storage/named_query.go
Improve the public plans interceptor  performance by listing plans visibilities without the labels
- Prepare a map of label-less visibilities instead of getting all plan visibilities labels
- Change list labels to list no labels 
* [x ] Refactoring
=> broker public plans interceptor list plan visibilities without the labels

api/filters/check_instance_visibility_filter.go, api/osb/check_instance_visibility_plugin.go, storage/named_query.go, storage/postgres/query_builder_test.go
Improve the check_instance_visiblity plugin and filter by checking for instance visibility without returning a full label list that matches a plan & platform visibility to sm.
Refracture the code to perform the visibility check on the DB layer (by using 2 named queries)
* [x ] Refactoring
=> Check for instance visibility without returning the label list to sm

api/filters/check_instance_visibility_filter.go
Always check for visibility even if the label value is empty.
=> fix check instance visibility

pkg/types/platform.go, storage/interceptors/secured_generate_credentials_interceptor.go, test/platform_test/platform_test.go, test/storage_test/storage_test.go
fix unique username for technical platforms
technical platform have empty username which causing unique constraint violation on second technical platform creation.
The fix is to add platform id in username column
=> fix unique username for technical platforms

docs/usage/example-usage.md
As pert of SAP re-branding of the SAP Cloud Platform to SAP BTP, we need to update the documentation
=> SAP CP re-branding to SAP BTP

Makefile
As gometalinter does not work with go modules, its binary can only be installed now if we set the GO111MODULE flag to off.
=> install go meta linter with gomod off

api/filters/check_platform_suspended_filter.go, pkg/sm/sm.go, pkg/types/platform.go, storage/postgres/keystore_test.go, storage/postgres/locker_test.go, storage/postgres/migrations/20210218104000_platform_suspended.down.sql, storage/postgres/migrations/20210218104000_platform_suspended.up.sql, storage/postgres/platform.go, test/osb_and_plugin_test/plugin_test/platform_suspended_plugin_test.go
Allow suspend platform by adding new boolean column to platform table,
Following OSB operations will be forbidden when the platform is suspended:
- Provision
- Deprovision
- Update
- Bind
- Unbind
=> support platform suspension

operations/scheduler.go
FIX: Use an existing named_query to retrieve the resource's last operation instead of loading a full operation list.
Check for existing operation only when is needed.
=> Fix last operation query (compare single objects instead of lists)

api/credentials_controller.go, test/osb_and_plugin_test/osb_test/catalog_test.go, test/test.go
don't allow update broker credentials on resync job
it's not really needed credentials will be rotated only on active broker update
=> don't allow update broker credentials on resync job

api/common/sharing/utils.go, test/service_instance_and_binding_test/service_instance_test/service_instance_test.go
Support the K8S polling mechanism for instance sharing.
Allow passing parameters on reference-instance patch request as long as the "referenced_instance_id" value has not changed.
=> allow updating reference instance when parameters are not changed.

api/api.go, api/info/info_controller.go, test/info_test/info_test.go
Allow developers to retrieve service manager tenant id for development/ configurations purposes .
Add service manager tenant  id to the info endpoint
=> add service manager tenant id to info endpoint

api/common/sharing/utils.go, api/osb/instance_sharing_plugin.go, storage/named_query.go, test/service_instance_and_binding_test/service_instance_test/service_instance_test.go
We do want to be case-sensitive for reference-instance provision by selectors.
Revert to the original selector feature without the ignore case named-queries.
=> Revert ignore case for reference provisioning

api/common/sharing/utils.go, pkg/instance_sharing/types.go, pkg/util/errors.go, schemas/predefined_plans.go, test/common/service_instance_sharing.go, test/osb_and_plugin_test/osb_test/instance_sharing_test.go, test/service_instance_and_binding_test/service_instance_test/service_instance_test.go
Sharing a service instance between different scopes allows apps in different scopes to share databases, messaging queues, and other types of services. This enables development teams to share resource, while eliminates the use service bindings as keys and user-provided services or other means to maintain credentials of instances which were provisioned in another scope.
As a developer, I would like to be able to refer to a shared instance without the need to provide the ID of the original instance so that I could apply a robust automated script that can be executed in different landscapes and setups
Implemented like the service plan selector
* Retrieve in advance the service instances that match the criteria of the labels.
* Filter the labeled instances comparing to the full list of shared …
=> Reference selectors with label query

pkg/auth/oidc/oidc_test.go, pkg/auth/util/util.go
Allow setting an OIDC client via file or string
Checks if the certificate & key input has `.pem` suffix -> read file.
else -> read input's value.
=> oidc add pem format validation

operations/maintainer.go, pkg/query/operators.go, pkg/query/selection.go, pkg/query/selection_test.go, sonar-project.properties, storage/postgres/query_builder.go, storage/postgres/where_clause_tree.go, storage/sub_query.go, test/query_test/query_test.go
SM ORM does not support sub-queries. Adding the functionality in order to solve performance issues with "exists queries"
Add new Criterion Type.
=> Fearure  orm support for subqueries
